[workspace]
authors = ["coda <dakotajayroth@gmail.com>"]
channels = ["conda-forge"]
name = "ResumeOptimizer"
platforms = ["osx-arm64", "linux-64" ]
version = "0.1.0"

[tasks]
dev = "python main.py"

[dependencies]
python = ">=3.13,<3.14"
yaml = ">=0.2.5,<0.3"

[pypi-dependencies]
rendercv = { version = ">=2.3, <3", extras = ["full"] }
openai = ">=2.9.0, <3"
pydantic = ">=2.12.5, <3"
pyyaml = ">=6.0.3, <7"
langfuse = ">=3.10.5, <4"
