[workspace]
authors = ["coda <dakotajayroth@gmail.com>"]
channels = ["conda-forge"]
name = "ResumeOptimizer"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
dev = "python main.py"

[dependencies]
python = ">=3.14.1,<3.15"

[pypi-dependencies]
rendercv = { version = ">=2.3, <3", extras = ["full"] }
openai = ">=2.9.0, <3"
pydantic = ">=2.12.5, <3"
